#!/usr/bin/ruby
# -*- coding: utf-8 -*-

require 'yaml'

docker_dir = '/Users/diverta/rcms/docker'
virtual_host_url = ARGV[0]

ports_config = YAML.load_file("#{docker_dir}/ports.yaml")
exit 0 if !ports_config
ssh_port = ports_config[virtual_host_url]
exit 0 if !ssh_port

system("ssh -i ~/.ssh/diverta 192.168.99.100 -p #{ssh_port} -l diverta")
