#!/bin/sh
# requirement: peco

USER=diverta
HOST=$(echo "$DOCKER_HOST" | awk '{print substr($0, 7)}' | awk -F: '{print $1}')
PORT=$(docker ps | tail -n +2 | grep rcms | peco | awk -F: '{print $2}' | awk -F- '{print $1}')

ssh $USER@$HOST -p $PORT -i ~/.ssh/id_rsa
